# Generated by Django 5.2.3 on 2025-06-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
